#!/bin/bash
# vim:ts=2
# program: Using to mount and umount ecryptfs dir
# made by: Engells
# date: Aug 17, 2024
# content:


#====副函式======================

_mode_select()
{
  case $way1 in
    mnte)
      _mnt_ecryptfs ;;
    umte)
      _umt_ecryptfs ;;
    mntl)
      _mnt_luks ;;
    umtl)
      _umt_luks ;;
    *)
      echo '未定義之處理方式, 兩秒鐘後離開程式...' && sleep 2 && exit 2
  esac
}


_mnt_ecryptfs()
{
  [[ -z $2 ]] || ${realdir}=$2
  [[ -z $3 ]] || ${emntdir}=$3
  [[ -z $4 ]] || ${epasswd}=$4
  echo "解鎖密鑰 ..."
  cd ${keysdir} && gpg -d ${epasswd}.gpg > ${epasswd} && cd ${homedir}
  echo "掛載目錄 ..." && sleep 2
  sudo modprobe ecryptfs && lsmod | grep ecryptfs
  sudo mount -t ecryptfs ${realdir} ${emntdir} -o \
  key=passphrase:passfile=${epasswd},ecryptfs_cipher=aes,ecryptfs_key_bytes=32,ecryptfs_passthrough=n,ecryptfs_enable_filename_crypto=y
  echo "掛載 ${emntdir} 完成 ..."
}


_umt_ecryptfs()
{
  [[ -z $3 ]] || ${emntdir}=$3
  echo "卸載目錄 ..." && sleep 2
  sudo umount -t ecryptfs ${emntdir}
  sudo modprobe -r ecryptfs
  echo "刪除密鑰 ..."
  sudo rm ${epasswd}
  echo "卸載完成 ..."
}


_mnt_luks()
{
  [[ -z $2 ]] || ${luksimg}=$2
  [[ -z $3 ]] || ${lmntdir}=$3
  [[ -z $4 ]] || ${lpasswd}=$4
  [[ -z $5 ]] || ${luksloop}=$5
  [[ -z $6 ]] || ${luksname}=$6
  echo "解鎖密鑰 ..."
  cd ${keysdir} && gpg -d ${lpasswd}.gpg > ${lpasswd} && cd ${homedir}
  echo "掛載磁區 ..." && sleep 2
  sudo losetup /dev/${luksloop} ${luksimg} && \
  sudo cryptsetup open -d ${lpasswd} /dev/${luksloop} ${luksname} && \
  sudo mount /dev/mapper/${luksname} ${lmntdir} && \
  echo "掛載 ${luksimg} 至 ${lmntdir} 完成 ..."
}


_umt_luks()
{
  [[ -z $3 ]] || ${lmntdir}=$3
  [[ -z $5 ]] || ${luksloop}=$5
  [[ -z $6 ]] || ${luksname}=$6
  echo "卸載磁區 ..." && sleep 2
  sudo umount ${lmntdir} && \
  sudo cryptsetup close ${luksname} && \
  sudo losetup -d /dev/${luksloop} && \
  echo "刪除密鑰 ..."
  sudo rm ${lpasswd}
  echo "卸載完成 ..."
}



#====程式主體=====================

homedir="/home/engells"
keysdir="${homedir}/.var/pwd"
realdir="/home/ktws/kth"
emntdir="/home/ktws/kth"
epasswd="${homedir}/.var/pwd/ecrypt.enc"
luksimg="${homedir}/mnt/tmpfs/kth.img"
lmntdir="${homedir}/mnt/dump3"
lpasswd="${homedir}/.var/pwd/luks.enc"
luksloop="loop0"
luksname="zmykth"

if [ -z $1 ]; then
  read -p '請輸入處理方式 mnte:掛載目錄 umte:卸載目錄 mntl:掛載磁區 umtl:卸載磁區  ::' way1  # des='xxxx' + printf "%s\n" "$des"
  if [ -z "$way1" ]; then echo '未選擇處理方式, 兩秒鐘後離開程式...' && sleep 2 && exit 1 ; fi

else
  way1=$1

fi

_mode_select

unset way1 ; unset homedir ; unset keysdir ; unset realdir ; unset emntdir ; unset epasswd
unset luksimg ; unset lmntdir ; unset lpasswd ; unset luksloop ; unset luksname
