#!/bin/bash
# vim:ts=2
# program: Using to mount and umount ecryptfs dir
# made by: Engells
# date: Mar 6, 2024
# content: gpg -d 指令需要 $HOME/.gnupg/ 存在，且該目錄不能為加密無法解讀狀態，故需中轉處理


#====副函式======================

_mode_select()
{
  case $way1 in
    mnte)
      _mnt_ecryptfs ;;
    umte)
      _umt_ecryptfs ;;
    *)
      echo '未定義之處理方式, 兩秒鐘後離開程式...' && sleep 2 && exit 2
  esac
}


_mnt_ecryptfs()
{
  [[ -z $2 ]] || ${realdir}=$2
  [[ -z $3 ]] || ${emntdir}=$3
  [[ -z $4 ]] || ${epasswd}=$4

  if [ -d ${gpgdir} ]
  then

    echo "解鎖密鑰 ..."
    cd ${keysdir} && gpg -d ${epasswd}.gpg > ${epasswd} && cd ${homedir}

    echo "掛載目錄..." && sleep 2
    sudo modprobe ecryptfs && lsmod | grep ecryptfs
    sudo mount -t ecryptfs ${realdir} ${emntdir} \
       -o key=passphrase:passfile=${epasswd} \
       -o ecryptfs_cipher=aes,ecryptfs_key_bytes=32,ecryptfs_passthrough=n,ecryptfs_enable_filename_crypto=y

    mv ${gpgdir}  ${trigdir}
    mv ${linkdir} ${gpgdir}

    sudo rm ${epasswd}

    echo "掛載完成..."

  else

    echo "Nothing to do!"

 fi
}


_umt_ecryptfs()
{
  [[ -z $3 ]] || ${emntdir}=$3

  if [ -h ${gpgdir} ]
  then

    echo "卸載目錄..." && sleep 2
    sudo umount -t ecryptfs ${emntdir}
    sudo modprobe -r ecryptfs

    echo "刪除密鑰"
    sudo rm ${epasswd}

    mv ${gpgdir}  ${linkdir}
    mv ${trigdir} ${gpgdir}

    echo "卸載完成..."

  else

    echo "Nothing to do!"

 fi
}


#====程式主體=====================

homedir="/home/engells"
realdir="${homedir}/mnt/xcfgs"
emntdir="${homedir}/mnt/xcfgs"
epasswd="${homedir}/.var/pwd/wind.enc"
gpgdir="${homedir}/.gnupg"
linkdir="${homedir}/.var/tmp/gnupg_link"
trigdir="${homedir}/.var/tmp/gnupg_trigger"


if [ -z $1 ]; then
  read -p '請輸入處理方式 mnte:掛載目錄 umte:卸載目錄  ::' way1  # des='xxxx' + printf "%s\n" "$des"
  if [ -z "$way1" ]; then echo '未選擇處理方式, 兩秒鐘後離開程式...' && sleep 2 && exit 1 ; fi

else
  way1=$1

fi

_mode_select

unset way1 ; unset homedir
unset realdir ; unset emntdir ; unset epasswd
unset gpgdir ; unset linkdir ; unset trigdir

