#!/bin/bash
# vim:ts=2
# program: Using to sync source_dir to target_dir
# made by: Engells
# date: Mar 4, 2024
# content: Move working dir name to wkgs


#====副函式======================

_mode_select()
{
  case $way1 in
    ktcfg)
      _back_ktcfg ;;
    *)
      echo '未定義之處理方式, 兩秒鐘後離開程式...' && sleep 2 && exit 2
  esac
}


_sync_act()
{
  sudo rsync -avuAHX ${surdir} ${tardir}
}


_back_ktcfg()
{
  echo "同步組態 ..."
  surdir="${homedir}/.config/zz_my_confs/"
  tardir="${homedir}/mnt/wkgs/scripts/confs_sys/"
  _sync_act

  echo "\n\n"
  echo "同步 vim 組態 ..."
  surdir="${homedir}/.config/zz_dot_files/"
  tardir="${homedir}/mnt/wkgs/scripts/confs_vim/"
  _sync_act

  echo "\n\n"
  echo "同步 Shell Scripts ..."
  surdir="${homedir}/mnt/xcmds/avails/"
  tardir="${homedir}/mnt/wkgs/scripts/sh_avails/"
  _sync_act

  echo "\n\n"
  echo "同步 Booting Scripts ..."
  sudo rsync -avuAHX ${homedir}/mnt/xcmds/avails/mnt_sec_init /opt/utils/zz_secinit.sh
  sudo rsync -avuAHX ${homedir}/mnt/xcmds/avails/mnt_dump_d   /opt/utils/zz_dumpd.sh
}


#====程式主體=====================

homedir=$HOME
surdir=""
tardir=""

if [ -z $1 ]; then
  read -p '請輸入處理方式 ktcfs:備份組態  ::' way1  # des='xxxx' + printf "%s\n" "$des"
  if [ -z "$way1" ]; then echo '未選擇處理方式, 兩秒鐘後離開程式...' && sleep 2 && exit 1 ; fi

else
  way1=$1

fi

_mode_select

unset way1 ; unset homedir ; unset surdir ; unset tardir
