#!/bin/bash
# vim:ts=2
# program:  將已經下載完成之檔案由 ~/downloads 移至 ~/mnt/buf ,注意 firefox 及 jdownload 下載中檔案附檔名為 .part , chromium 則為 .crdownload
# made by: Engells
# date: Feb 16, 2024
# content: 

SAVEIFS=$IFS  #新增變數 SAVEIFS，把原本的IFS值儲存起來。
IFS=$'\t\n'   #將IFS的值改掉
dname='/home/engells'

if [ -d ${dname}/downloads ]
then
  cd ${dname}/downloads
  for fname in $( ls ${dname}/downloads/ | grep -v '.part$' | grep -v '.crdownload$' )
  do
    sudo chown engells:engells ${dname}/downloads/${fname}
    sudo chmod +w ${dname}/downloads/${fname}
    if [ ! -d ${dname}/downloads/${fname} ] ; then mv ${dname}/downloads/${fname} ${dname}/mnt/buf/${fname} ; fi
    echo "moving ${fname} ..."
  done
else
  echo "There is no directory: ${dname}/downloads/"
fi

IFS=$SAVEIFS
cd ${dname}

exit 0
