#!/bin/bash
# vim:ts=2
# program: 將已下載完成的檔案由 $HOME/downloads 移至 $HOME/mnt/buf ,注意 firefox 及 jdownload 下載中檔案附檔名為 .part , chromium 則為 .crdownload
# made by: Engells
# date: Mar 1, 2024
# content: 

saveifs=$IFS  # 新增變數 saveifs，把原本的 IFS 值儲存起來。
IFS=$'\t\n'   # 將 IFS 的值改掉
surdir='/home/engells/downloads'
tardir='/home/buffer'

if [ -d ${surdir}/ ]
then
  cd ${surdir}/
  for fname in $( ls ${surdir}/ | grep -v '.part$' | grep -v '.crdownload$' )
  do
    sudo chown engells:engells ${surdir}/${fname}
    sudo chmod +w ${surdir}/${fname}
    if [ ! -d ${surdir}/${fname} ] ; then mv ${surdir}/${fname} ${tardir}/${fname} && echo "moving ${fname} ..." ; fi
  done
else
  echo "There is no directory: ${surdir}/"
fi

IFS=$saveifs
cd ${surdir}/ && cd ../

unset saveifs ; unset surdir ; unset tardir ; unset fname

exit 0

