#!/bin/bash
# program: Using to dump ktwsb partition to portable disk
# made by: Engells
# date: Oct 28, 2023
# content: 

gnome-terminal -- bash /home/engells/ktws/scripts/avails/nautilus_lunch.sh dk1 2>/home/engells/zz
