#!/bin/bash
# vim:ts=4
# program: to download many files form internet
# made by: Engells
# date: Jul 20, 2013
# content:
#	1.預先準備樣本來源檔:$dataInp，經中介檔案 $dataTra，產生下載清單檔案 $dataOut。呼叫 _dl_files_bunch, _build_sur_bunch
#	2.自 $dataOut 逐列建立新目錄，進入新目錄準備下載圖檔
#	3.artnude來源，組合出 http://artnudegalleries.net/galleries/amourangels/xxx/[1-20].jpg 網址並依序下載圖檔
#	  eroluv來源，組合出 http://cdn.eroluv.com/g-metart/m131/pics/pics5.jpg 網址並依序下載圖檔
#	4.修改檔名流水編號，呼叫 _rename_file_full_bunch
#	5.修改檔名，呼叫 _rename_file_full_bunch
#	6.原則上應該盡採多重路徑下載模式，但為維持彈性，仍保留單一路徑下載模式保留

#====副函式======================

_init_dl()
{
work_dir="/home/engells/mnt/buf/photos"
[ -d $work_dir ] || mkdir -p $work_dir
dataInp=$work_dir/f_inp
dataTra=$work_dir/f_trn
dataOut=$work_dir/f_out

case $way1 in
	da)
		_start_dl_alone ;;
	db)
		_start_dl_bunch ;;
	rd)
		_rename_file_digit ;;
	rf)
		_rename_file_full ;;
	*)
		echo " " > /dev/null
esac
}

_start_dl_alone()
{
ori_dir=""
new_dir=Metart_$(echo $ori_dir | sed 's/-/\_/g')
mkdir $new_dir
cd $new_dir

case $way2 in
	artnude)
		url_prefix="http://artnudegalleries.net/galleries/amourangels/"
		begNum="1"
		endNum="20"
		_dl_files_artnude_alone ;;
	eroluv)
		url_prefix="http://cdn.eroluv.com/g-metart/"
		begNum="1"
		endNum="16" 
		_dl_files_eroluv_alone ;;
	*)
		echo " " > /dev/null
esac

cd ..
}

_start_dl_bunch()
{
case $way2 in
	artnude)
		url_prefix="http://artnudegalleries.net/galleries/amourangels/"
		begNum="1"
		endNum="20"
		_build_sur_bunch ;;
	eroluv)
		url_prefix="http://cdn.eroluv.com/g-metart/"
		begNum="1"
		endNum="16" 
		_build_sur_bunch;;
	*)
		echo " " > /dev/null
esac
}

_build_sur_bunch()
{
# 將url_prefix 變數所引用的網址中有斜線及點符號的前方加上反斜線，供後續 sed 處理，最終組成目錄清單，各目錄以空格分開
url_string=$(echo $url_prefix | sed 's/\//\\\/ /g' | sed 's/\./\\\. /g' | sed 's/ //g')

# 將 'xxx/1.jpg' 字串，保留 'xxx' 作為目錄名稱
sed "s/$url_string//g" $dataInp | sed 's/\/.*jpg/ /' > $dataTra

# 以 tr 指令恢復斷行
cat $dataTra | tr -d $'\n' > $dataOut

[ -d /home/engells/mnt/buf/Photo ] || mkdir -p /home/engells/mnt/buf/Photo
cd /home/engells/mnt/buf/Photo

_dl_files_bunch
}

_dl_files_bunch()
{
for ori_dir in $(cat $dataOut)
do
	new_dir=Metart_$(echo $ori_dir | sed 's/-/\_/g')
	mkdir $new_dir
	cd $new_dir

	case $way2 in
		artnude)
			_dl_files_artnude_alone ;;
		eroluv)
			_dl_files_eroluv_alone ;;
		*)
			echo " " > /dev/null
	esac

	cd ..
done
}

_dl_files_artnude_alone()
{
for ((i=$begNum; i<=$endNum; i=i+1))
do
	#if ((i<10)); then
	#  url_full="${url_prefix}${ori_dir}/0${i}.jpg
	#else
	  url_full=${url_prefix}${ori_dir}/${i}.jpg
	#fi
	 wget $url_full
done
}

_dl_files_eroluv_alone()
{
for ((i=$begNum; i<=$endNum; i=i+1))
do
	#if ((i<10)); then
	#  url_full="${url_prefix}${ori_dir}/0${i}.jpg
	#else
	  url_full=${url_prefix}${ori_dir}/pics/pics${i}.jpg
	#fi
	wget $url_full
done
rename 's/pics//g' *.jpg		# rename 's/^0//' *.jpg
}

_rename_file_digit()
{
echo ''; echo 'start to add digit to file name ...'; echo ''; sleep 2

cd $work_dir

for d in $(ls ./)
do
	if [ -d $d ]; then
		cd $d

		for f in $(ls ./)
		do
			pre_fix=${f%.*}	# 取 1.jpg 的 1
			suf_fix=${f#*.}	# 取 1.jpg 的 jpg

			if (( $pre_fix < 10)); then mv $f 0$pre_fix.$suf_fix; fi
		done

		cd ..
	fi
done
}

_rename_file_full()
{
echo ''; echo 'start to change file full name ...'; echo ''; sleep 2

cd $work_dir

for d in $(ls ./)
do
	if [ -d $d ]; then
		cd $d

		for f in $(ls ./)
		do
			[[ "$f" !=  "$d-$f" ]] && mv $f $d-$f
		done

		cd ..
	fi
done
}

#====程式主體=====================

if [ -z $2 ]; then 
	Des1='請輸入作業方式 da:單一路徑下載 db:多重路徑下載 rd:修改檔案序號 r2:修改完整檔名'
	printf "%s\n" "$Des1"

	read way1
	if [ -z "$way1" ]; then echo '未選擇處理方式, 兩秒鐘後離開程式...' && sleep 2 && exit 1 ; fi
else
	way1=$1
fi


if [ -z $2 ]; then 
	Des2='請輸入來源網站 artnude eroluv'
	printf "%s\n" "$Des2"

	read way2
	if [ -z "$way2" ]; then echo '未選擇處理方式, 兩秒鐘後離開程式...' && sleep 2 && exit 1 ; fi
else
	way2=$2
fi

_init_dl

[ -f $dataInp ] && rm $dataInp
[ -f $dataTra ] && rm $dataTra
[ -f $dataOut ] && rm $dataOut

unset work_dir; unset ori_dir; unset new_dir
unset dataInp; unset dataTra; unset dataOut
unset url_full; unset url_prefix; unset url_string
unset begNum; unset endNum
unset i; unset d; unset f

