#!/bin/bash
# vim:ts=2
# program:  將已經下載完成之檔案由 ~/downloads 移至 ~/mnt/buf ,注意 firefox 及 jdownload 下載中檔案附檔名為 .part , chromium 則為 .crdownload
# made by: Engells
# date: Feb 8, 2024
# content: 

cd /home/engells/downloads
SAVEIFS=$IFS  #新增變數 SAVEIFS，把原本的IFS值儲存起來。
IFS=$'\t\n'   #將IFS的值改掉

for fname in $( ls . | grep -v '.part$' | grep -v '.crdownload$' )
do
  echo $fname
	sudo chown engells:engells $fname
	sudo chmod +w $fname
  if [ ! -d $fname ] ; then mv $fname /home/engells/mnt/buf/$fname ; fi
done

IFS=$SAVEIFS
cd /home/engells

exit 0
