#!/bin/bash
# program: Using to open a terminal running  tumx server with one window and three panels
# made by: Engells
# date: Mar 30, 2019
# content: 

#cd $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
tmux select-window -t first_session:0
tmux split-window -v -p 40
tmux split-window -h -p 40
#tmux split-window -h 'exec pfoo "bundle exec compass watch"'
#tmux split-window -v -t 0 'exec pfoo "rake ts:start"'
