#! /bin/bash
# program: Using to open a terminal running vim
# made by: Engells
# date: Mar 30, 2019
# content: 

gnome-terminal --geometry=124x48+30+30 -e 'vim'
#gnome-terminal --geometry=124x48+30+30 -x vim		# work just as the above line
