#!/bin/bash
# program: Using to dump ktws partition to portable disk
# made by: Engells
# date: Mar 30, 2019
# content: 

gnome-terminal -e '/home/engells/ktws/scripts/avails/nautilus_lunch.sh dc1' 2>/home/engells/zz
