
[[ ! -f $HOME/.config/z_my_confs/shell_basic ]] || source $HOME/.config/z_my_confs/shell_basic
[[ ! -f $HOME/.config/z_my_confs/shell_alias ]] || source $HOME/.config/z_my_confs/shell_alias

[[ $(echo $PATH | grep "/home/utils/poetry/bin") ]] || PATH=/home/utils/poetry/bin:$PATH
[[ $(echo $PATH | grep "$HOME/.local/bin") ]] || PATH=$HOME/.local/bin:$PATH

PS1='\033[01;32m\]\u@\h \033[01;34m\]\W\033[0m\]\$ '


