#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "Arch Linux on sdb2" {
        load_video
        set gfxpayload=keep
        insmod gzio
        insmod part_gpt
        insmod btrfs
        search --no-floppy --fs-uuid --set=root 82c32523-4ef4-4f28-95a6-fe081fb27828
        echo    'Loading Linux linux ...'
        linux   /os/arch/boot/vmlinuz-linux root=UUID=82c32523-4ef4-4f28-95a6-fe081fb27828 rw rootflags=subvol=os/arch  loglevel=3
        echo    'Loading initial ramdisk ...'
        initrd  /os/arch/boot/intel-ucode.img /os/arch/boot/initramfs-linux.img
}

menuentry "Linux Mint 21.3 Cinnamon on sda2" {
        recordfail
        load_video
        gfxmode $linux_gfx_mode
        insmod gzio
        if [ x$grub_platform = xxen ]; then insmod xzio; insmod lzopio; fi
        insmod part_gpt
        insmod ext2
        search --no-floppy --fs-uuid --set=root 75b0d30f-c21d-467a-b5cd-ab9510b576ae
        echo    'Loading Linux vmlinuz ...'
        linux   /boot/vmlinuz-5.15.0-91-generic root=UUID=75b0d30f-c21d-467a-b5cd-ab9510b576ae
        echo    'Loading initial ramdisk ...'
        initrd  /boot/initrd.img-5.15.0-91-generic
}

menuentry "Install Archlinux_20240201_x64" {
  set gfxpayload=keep
  insmod part_gpt
  insmod ext2
  search --set=root --no-floppy --fs-uuid e6afba18-d2cd-4e15-82ce-4c4592ba6390
  loopback loop /ArchLinux.iso
  linux (loop)/arch/boot/x86_64/vmlinuz-linux img_dev=UUID=e6afba18-d2cd-4e15-82ce-4c4592ba6390 img_loop=/ArchLinux.iso earlymodules=loop
  initrd (loop)/arch/boot/intel-ucode.img (loop)/arch/boot/amd-ucode.img (loop)/arch/boot/x86_64/initramfs-linux.img
}

menuentry "Install Ubuntu 22.04 from sda4" {
  set gfxpayload=keep
  insmod part_gpt
  insmod ext2
  search --set=root --no-floppy --fs-uuid e6afba18-d2cd-4e15-82ce-4c4592ba6390
  loopback loop /Jammy.iso
  linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=/Jammy.iso noeject nopromt
  initrd (loop)/casper/initrd
}

menuentry "Install Mint 21.2 from sda4" {
  set gfxpayload=keep
  insmod part_gpt
  insmod ext2
  set root=(hd0,gpt4)
  loopback loop (hd0,gpt4)/Victoria.iso
  linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=/Victoria.iso noeject nopromt
  initrd (loop)/casper/initrd.lz
}

