#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "Install Ubuntu 18.04.2 from /dev/sda" {
  	loopback loop (hd1,9)/Bionic_x64.iso
	linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=/Bionic_x64.iso noeject nopromt
	initrd (loop)/casper/initrd
}

menuentry "Install Ubuntu 18.04.2 from /dev/sdb" {
  	loopback loop (hd0,10)/Bionic_x64.iso
	linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=/Bionic_x64.iso noeject nopromt
	initrd (loop)/casper/initrd
}

menuentry "Install Ubuntu 20.04.4 from sda5" {
  loopback loop (hd0,5)/Focal.iso
  linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=/Focal.iso noeject nopromt
  initrd (loop)/casper/initrd
}

menuentry "Install Ubuntu 20.04.4 from sdb6" {
  loopback loop (hd1,6)/Focal.iso
  linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=/Focal.iso noeject nopromt
  initrd (loop)/casper/initrd
}

