#!/bin/bash

sudo bash /opt/security/iptables/iptables.rule
sudo systemctl restart lxc-net

#bash /opt/engells/z_myload.sh

for SUBDIR in z_cache z_cache/home z_cache/cntrb z_cache/cntrp z_downloads z_tmpfs z_tmpfs/cntrb z_tmpfs/cntrp z_tmpfs/firefox z_tmpfs/chromium
do
	[ -d /tmp/$SUBDIR ] || sudo mkdir -p /tmp/$SUBDIR
	sudo chown -R engells:engells /tmp/$SUBDIR
	chmod 1777 /tmp/$SUBDIR
done

echo "Something done while booting on $(date)" >> /home/engells/z_boot.log

exit 0

