#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will “exit 0” on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

bash /opt/security/iptables/iptables.rule
bash /opt/engells/z_myload.sh

echo "Set firewall and restore log files on $(date)" >> /home/engells/my_boot.log
systemctl restart lxc-net

exit 0
