#!/bin/bash
#
# This script will deny some IPs that I don't want it IN
#
# HISTORY
# 2002/03/05	first release by VBird
# 2002/08/20	revise	      by VBird

# 140.116.44.x 為成大環工之主機位址，網路作者鳥哥在防火牆範例中用來作設定之例子。
# iptables -A INPUT	  -i $EXTIF -s 140.116.44.125  -j DROP

