#!/usr/bin/env zsh

################################
## EXPORT ENVIRONMENT VARIABLE #
################################

#Ref URL:
# https://thevaluable.dev/zsh-install-configure-mouseless/
# https://github.com/Phantas0s/.dotfiles/blob/master/zsh/zshenv
# https://wiki.archlinux.org/title/XDG_Base_Directory

#export TERM='rxvt-256color'  # 'xterm-256color' 'screen-256color'
#export DOTFILES="$HOME/.dotfiles"
#export WORKSPACE="$HOME/workspace"

#[ -f "$DOTFILES/install_config" ] && source "$DOTFILES/install_config"

## XDG
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state

## editor
export EDITOR="vim"
#export VISUAL="nvim"

## zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath
export HISTSIZE=300                     # Maximum events for internal history
export SAVEHIST=300                     # Maximum events in history file

## other software
#export TMUXP_CONFIGDIR="$XDG_CONFIG_HOME/tmuxp"
#export COMPOSER_HOME="$XDG_CONFIG_HOME/composer"
#export I3_CONFIG="$XDG_CONFIG_HOME/i3"
#export VIMCONFIG="$XDG_CONFIG_HOME/nvim"
#export GIMP_VERSION="2.10"
#export SCREENSHOT="$HOME/Documents/images/screenshots"

## Man pages
#export MANPAGER='nvim +Man!'

## fzf
#export FZF_DEFAULT_COMMAND='rg --files --hidden --glob "!.git"'
#export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

#FZF_COLORS="bg+:-1,\
#fg:gray,\
#fg+:white,\
#border:black,\
#spinner:0,\
#hl:yellow,\
#header:blue,\
#info:green,\
#pointer:red,\
#marker:red,\
#prompt:gray,\
#hl+:red"

#export FZF_DEFAULT_OPTS="--height 60% \
#--border sharp \
#--color='$FZF_COLORS' \
#--prompt '∷ ' \
#--pointer ▶ \
#--marker ⇒"
#export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -n 10'"

## export FZF_TMUX_OPTS="-p"

## X11
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"

## Racket
#export PLTUSERHOME="$XDG_DATA_HOME/racket"

## golang
#export GOPATH="$WORKSPACE/go"
#export GOBIN="$WORKSPACE/go/bin"
#export GOCACHE="$XDG_CACHE_HOME/go-build"

## NPM
#export NPM_PATH="$XDG_CONFIG_HOME/node_modules"
#export NPM_BIN="$XDG_CONFIG_HOME/node_modules/bin"
#export NPM_CONFIG_PREFIX="$XDG_CONFIG_HOME/node_modules"

## git
#export GIT_REVIEW_BASE=master # See gitconfig

## PATH
#export PATH="$COMPOSER_HOME/vendor/bin:$PATH"                       # COMPOSER
#export PATH="$GOBIN:$PATH"                                          # GOBIN
#export PATH="$NPM_BIN:$PATH"                                        # NPM

## Cloud
#source $CLOUD/development/env

