#!/bin/sh
# vim:ts=4
### BEGIN INIT INFO
# Provides:         engells
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# X-Start-Before:
# X-Stop-After:
# Default-Start:    1 2 3 4 5
# Default-Stop:     0 6
### END INIT INFO

SCRIPTNAME=/etc/init.d/z_myload.sh

_dump2bak()
{
sudo rm -rf $tardir/*
cd $surdir
sudo cp -R . $tardir
}

_chg_owner()
{
chown -R engells:engells $surdir
chown -R engells:engells $tardir
}

case "$1" in
  start)
	for way in varlog userdl
	do
		case $way in
			varlog)
				# to reload /var/log
				surdir=/var/backups/log
				tardir=/var/log
				_dump2bak
				;;
			userdl)
				# to reload ~/downloads
				surdir=/home/engells/mnt/bak
				tardir=/home/engells/downloads
				_dump2bak
				_chg_owner
				;;
			cache)
				# to reload ~/.cache
				surdir=/home/engells/mnt/cache
				tardir=/home/engells/.cache
				_dump2bak
				_chg_owner
				;;
			samba)
				# disable samba servive after booting
				service smbd stop
				service nmbd stop
				;;
			*)
				echo '' > /dev/null
		esac
	done
        ;;
  stop|restart|force-reload|status)
	for way in varlog userdl
	do
		case $way in
			varlog)
				# to backup /var/log
				surdir=/var/log
				tardir=/var/backups/log
				_dump2bak
				;;
			userdl)
				# to backup ~/downloads
				surdir=/home/engells/downloads
				tardir=/home/engells/mnt/bak
				_dump2bak
				_chg_owner
				;;
			cache)
				# to backup ~/.cache
				surdir=/home/engells/.cache
				tardir=/home/engells/mnt/cache
				_dump2bak
				_chg_owner
				;;
			*)
				echo '' > /dev/null
		esac
	done
	;;
  *)
	;;
esac

unset way; unset surdir ; unset tardir

