#! /bin/sh
### BEGIN INIT INFO
# Provides:          engells
# Should-Start:      
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     1 2 3 4 5
# Default-Stop:      0 6
# Short-Description: Dump and load tmpfs files
# Description:       
### END INIT INFO
#
# Author:       me <xxx@yyy.zzz>
#

. /lib/lsb/init-functions

case "$1" in
  start)
    echo ">>>>>" >> /home/engells/ab
  ;;
  stop|restart|force-reload)
    echo "<<<<<" >> /home/engells/ab
  ;;
  *)
    echo "Do nothing about dump and load tmpfs files"
    exit 1
  ;;
esac

exit 0
