#!/bin/sh
# vim:ts=2
# program: To backup tmpfs while halting
# made by: Engells
# date: Jun 30, 2022
# content: 

_dump2bak()
{
rm -rf $tardir/*
cd $surdir
cp -R . $tardir
}

_chg_owner()
{
chown -R engells:engells $surdir
chown -R engells:engells $tardir
}

for way in varlog userdl
do
	case $way in
		varlog)
			# to backup /var/log
			surdir=/var/log
			tardir=/var/backups/log
			_dump2bak
			;;
		userdl)
			# to backup ~/downloads
			surdir=/home/engells/downloads
			tardir=/home/engells/mnt/bak
			_dump2bak
			_chg_owner
			;;
		cache)
			# to backup ~/.cache
			surdir=/home/engells/.cache
			tardir=/home/engells/mnt/cache
			_dump2bak
			_chg_owner
			;;
		*)
			echo '' > /dev/null
	esac
done

unset way; unset surdir ; unset tardir

echo "Save log and cache files to local dusk on $(date)" >> /home/engells/z_boot.log

exit 0

